# Site settings
title: David Chiles
email: david@davidchiles.org
description: > # My thoughts on maps, iOS development and a bit of camping.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://davidchiles.org" # the base hostname & protocol for your site
twitter_username: dchiles
github_username:  davidchiles
instagram_username: chilichiles

# Build settings
# Jekyll 3 now only supports Kramdown for Markdown
markdown: kramdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
